name = "website-sun-pool-17-preview"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-sun-pool-17-preview-inventory"
database_id = "c1db2f6a-a617-4aa4-afc3-25b08482767d"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "website-sun-pool-17-images"

[[kv_namespaces]]
binding = "SESSION"
id = "97b0f5cddbd44c84948b28009f4eaa07"
