// Generated by Site Launchpad. Edit in the dashboard and export again.
import type { ClientConfigInput } from "./schema";

export const rawClientConfig: ClientConfigInput = {
  "deployMode": "client",
  "identity": {
    "name": "Sun Pool & Spa Supply",
    "shortName": "Sun Pool",
    "foundedYear": 1978,
    "tagline": "The best hot tub and swim spa store in San Diego County. Real units on the floor.",
    "siteUrl": "https://www.sunpoolandspasupply.com",
    "schemaType": "Store"
  },
  "contact": {
    "phone": "+16195618587",
    "phoneDisplayOverride": "(619) 561-8587",
    "smsPhone": "+16195618587",
    "email": "info@sunpoolandspasupply.com"
  },
  "address": {
    "street": "12473 Woodside Ave",
    "street2": "Suite C",
    "city": "Lakeside",
    "region": "CA",
    "postalCode": "92040",
    "country": "US",
    "latitude": 32.857086,
    "longitude": -116.924479,
    "googlePlaceId": null
  },
  "hours": [
    {
      "days": [
        "Monday"
      ],
      "opens": "09:30",
      "closes": "17:00"
    },
    {
      "days": [
        "Tuesday"
      ],
      "opens": "09:30",
      "closes": "17:00"
    },
    {
      "days": [
        "Wednesday"
      ],
      "opens": "09:30",
      "closes": "17:00"
    },
    {
      "days": [
        "Thursday"
      ],
      "opens": "09:30",
      "closes": "17:00"
    },
    {
      "days": [
        "Friday"
      ],
      "opens": "09:30",
      "closes": "17:00"
    },
    {
      "days": [
        "Saturday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Sunday"
      ],
      "opens": "10:00",
      "closes": "14:00"
    }
  ],
  "social": {
    "facebook": null,
    "instagram": null,
    "youtube": null,
    "tiktok": null,
    "x": null,
    "linkedin": null,
    "googleBusiness": null
  },
  "brand": {
    "colors": {
      "primary": "#087F8C",
      "primaryMid": "#066875",
      "deep": "#064F5B",
      "night": "#043A43",
      "abyss": "#02272E",
      "accent": "#45D6C6",
      "accentSoft": "#83E7DC",
      "accentDeep": "#22B7A7",
      "accentDark": "#08766D",
      "accentLift": "#9AF0E7",
      "accentPress": "#20AFA1",
      "accentGlow": "#C5F8F3",
      "urgent": "#D7261E",
      "urgentLight": "#E8382F",
      "urgentDark": "#B71E17",
      "surface": "#FFFFFF",
      "surfaceAlt": "#EFFBFA",
      "ink": "#141927",
      "inkMuted": "#4A5268",
      "onDark": "#D4F5F2",
      "onDarkMuted": "#9BCFC9"
    },
    "fonts": {
      "display": "Outfit",
      "body": "Outfit",
      "mono": "Spline Sans Mono",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;500;600;700;800&family=Instrument+Sans:wght@400;500;600;700&family=Spline+Sans+Mono:wght@400;500;700&display=swap"
    },
    "logos": {
      "nav": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/astro/navLogo-82278ee5716f7b8a373c952fb7dea8856548541160095f7b3c6584e6cf70e031-80d96e3b27f845c5a859862bea9e71e6.webp",
      "footer": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/astro/footerLogo-985bda4c93f6085db7bddb81707a54265f8c70ed4eda3772b9d6d0d43f8e261b-989f8691842d41bdaf0e57ae93b52503.webp",
      "inventory": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/astro/inventoryLogo-ea13f6dc3ad99f7d251078bfa5b69ba7fa822ba207ff1bc09643641937426357-efdf389030c74c45bbbda8d7c5de1143.webp",
      "favicon": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/astro/favicon-82e34046a951c9048bd0584ce6ba1ee3429d3cc9f3d80d7c16b8206d074fe623-554bb3017e7c4da3a7d50ceeb7d3e376.webp",
      "ogImage": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/astro/ogImage-3a1f93725ddeab68b111fd4ab5584a8295fc1233893a7623ec4ceb9db30e0830-0b79576c6242436597e2611233c025d0.webp"
    },
    "radius": {
      "card": 24,
      "button": 12,
      "pill": 999
    }
  },
  "nav": {
    "items": [
      {
        "type": "categories"
      },
      {
        "type": "link",
        "label": "Find Your Match",
        "href": "/find-your-match",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Inventory",
        "href": "/inventory",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Visit Us",
        "href": "/visit-us",
        "inHeader": true,
        "inFooter": true
      }
    ],
    "primaryCta": {
      "label": "Shop Inventory",
      "href": "/inventory"
    },
    "legalItems": [
      {
        "label": "Privacy Policy",
        "href": "/privacy-policy"
      }
    ]
  },
  "categories": {
    "hot-tub": {
      "enabled": true,
      "label": "Hot Tubs",
      "blurb": "Premium hot tubs for relaxation and recovery.",
      "heroImage": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/astro/categoryHotTubs-5fe55d9a6733a9f8a0116b3d525a6230b3488aef6b82a62320bf54bc196c2302-cb05c69b662848a9a9d5c58e52309fd9.webp",
      "sortOrder": 0
    },
    "swim-spa": {
      "enabled": true,
      "label": "Swim Spas",
      "blurb": "Swim, exercise, and relax year-round in your own backyard.",
      "heroImage": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/astro/categorySwimSpas-6ecefe660752d973bfbf23325e47bd4e62720a81b22d69ec27d34e5a7f80f5c2-71e74c5fb1a1436fadd235376555b858.webp",
      "sortOrder": 1
    }
  },
  "serviceAreas": [
    "Lakeside",
    "El Cajon",
    "Santee",
    "East County San Diego"
  ],
  "financing": null,
  "display": {
    "showPrice": true,
    "showMonthly": false
  },
  "homepage": {
    "title": null,
    "description": null,
    "sections": [
      {
        "type": "announcement",
        "badge": "Evergreen Catalog",
        "text": "Shop hot tubs",
        "href": "/hot-tubs"
      },
      {
        "type": "hero",
        "eyebrow": "San Diego County",
        "headline": "The Best Hot Tub & Swim Spa Store in San Diego County",
        "highlight": [
          "San Diego County"
        ],
        "subhead": "Real units on the floor. Serving East County since 1978.",
        "bullets": [],
        "backgroundImage": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/assets/hero-01e200d8fa7b1a6740face7fb5328faf675d9243ab75ab9afc281f7ad98d6d34-558cde56e213454cbc8960a5baaf4007.webp",
        "image": null,
        "promo": "Evergreen Catalog: There has never been a better time to buy a hot tub",
        "actions": [
          {
            "label": "Shop Inventory",
            "href": "/inventory",
            "style": "primary"
          },
          {
            "label": "Request Pricing",
            "href": "/find-your-match",
            "style": "secondary"
          }
        ],
        "leadCard": {
          "heading": "Get today's local price",
          "subtext": "Tell us what you're looking for and we'll text you current pricing and availability.",
          "footnote": "What happens next: we'll text you current pricing and availability, then you decide if a showroom visit makes sense. No pressure, no spam."
        }
      },
      {
        "type": "stats",
        "items": [
          {
            "value": "5★",
            "label": "Highly rated service",
            "claim": null
          },
          {
            "value": "100%",
            "label": "Out-the-door pricing",
            "claim": null
          },
          {
            "value": "0",
            "label": "Pressure on our floor",
            "claim": null
          },
          {
            "value": "1",
            "label": "Visit is all it takes",
            "claim": null
          }
        ]
      },
      {
        "type": "offercard",
        "eyebrow": "Open year-round in Lakeside",
        "heading": "There has never been a better time to buy a hot tub",
        "body": "Come see real units running on our floor, talk to the same family that has served East County, and get out-the-door pricing with nothing hidden.",
        "bullets": [
          {
            "text": "Working models on the showroom floor — see and feel the jets before you buy",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Out-the-door pricing that includes delivery and professional installation",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Flexible financing available for all credit types",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Local service after the sale from the team that installed it",
            "superlative": false,
            "footnote": null
          }
        ],
        "actions": [
          {
            "label": "Shop Available Inventory",
            "href": "/inventory",
            "style": "primary"
          },
          {
            "label": "Request Pricing",
            "href": "/find-your-match",
            "style": "secondary"
          }
        ]
      },
      {
        "type": "products",
        "eyebrow": "In stock · no waiting",
        "heading": "Showroom Selection",
        "body": "Explore selected showroom models and ask our team about current availability.",
        "limit": 4,
        "category": null,
        "moreLink": {
          "label": "See everything in stock",
          "href": "/inventory",
          "style": "primary"
        },
        "disclaimer": "Subject to credit approval. Terms and availability vary — ask in store for current offers."
      },
      {
        "type": "imagecards",
        "eyebrow": "Find your fit",
        "heading": "What are you shopping for?",
        "items": [
          {
            "title": "Hot Tubs",
            "body": "Premium hot tubs for relaxation and recovery.",
            "image": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/assets/hotTubs-8741f045aeda851c173ea9874fbaa8ce9edc0255e9965f75ce1bc817c7a1731b-cf8edb978b5f462d8acd8a3519209913.webp",
            "href": "/hot-tubs"
          },
          {
            "title": "Swim Spas",
            "body": "Swim, exercise, and relax year-round in your own backyard.",
            "image": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/assets/swimSpas-c6127ce457b5f860b52d42c640bbf38b9a8d61a070997ac864ecda891f78e45a-10064e2309b745e2ab9a0982ef27b43a.webp",
            "href": "/swim-spas"
          },
          {
            "title": "Find Your Match",
            "body": "Not sure which fits? Take the 60-second quiz.",
            "image": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-676367cea9036e636918533e76ab4b10b05dde8401c4185a6886060e9fb17e48-e76d8e060c554556ae747461723da420.webp",
            "href": "/find-your-match"
          }
        ]
      },
      {
        "type": "reviews",
        "eyebrow": "Reviews",
        "heading": "Customer Reviews",
        "items": [
          {
            "name": "Karen",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "July 2026",
            "location": null,
            "detail": null
          },
          {
            "name": "Andy",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "July 2026",
            "location": null,
            "detail": null
          },
          {
            "name": "Meagan",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "July 2026",
            "location": null,
            "detail": null
          }
        ],
        "aggregate": {
          "rating": 4.7,
          "count": 48,
          "source": "Google"
        }
      },
      {
        "type": "comparison",
        "eyebrow": "Why buy local",
        "heading": "Why Choose Us",
        "body": "We're a family-owned business dedicated to our community.",
        "usLabel": null,
        "themLabel": "Everyone else",
        "rows": [
          {
            "label": "Try before you buy",
            "us": "Real units on the floor to see and touch",
            "them": "Photos and specs on a screen"
          },
          {
            "label": "Pricing",
            "us": "Out-the-door price in writing",
            "them": "Freight, crane, and setup surprises later"
          },
          {
            "label": "Delivery & setup",
            "us": "Local crew that knows your area",
            "them": "Curbside drop-off — the rest is on you"
          },
          {
            "label": "After the sale",
            "us": "A local team that answers the phone",
            "them": "A 1-800 number and a ticket queue"
          }
        ]
      },
      {
        "type": "promise",
        "badgeValue": "100%",
        "badgeLabel": "Local promise",
        "heading": "Straight answers, no pressure",
        "body": "We'd rather earn a neighbor than push a sale. Come in with questions and leave with real numbers — what you do next is up to you.",
        "bullets": [
          {
            "text": "Out-the-door pricing in writing",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "No pressure, no hard sell",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Local delivery and setup guidance",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Real people after the sale",
            "superlative": false,
            "footnote": null
          }
        ]
      },
      {
        "type": "ctaband",
        "eyebrow": "Easy financing",
        "heading": "See Your Financing Options",
        "body": "Flexible monthly options can make the right spa fit your budget. Check your options in a couple of minutes — asking won't affect your credit.",
        "actions": [
          {
            "label": "Check my options",
            "href": "/find-your-match",
            "style": "primary"
          }
        ],
        "footnote": "Subject to credit approval. Terms and availability vary — ask in store for current offers.",
        "tone": "dark"
      },
      {
        "type": "gallery",
        "heading": "On the Lakeside floor",
        "images": [
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-676367cea9036e636918533e76ab4b10b05dde8401c4185a6886060e9fb17e48-e76d8e060c554556ae747461723da420.webp",
            "alt": "Family swimming in a Hydropool AquaTrainer"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-6f90855129dff8344b3fa53d0dbde3002d4b695aaf418a87b6ac69f8e53e80b9-c0adf5a9adf5480ab52877b7e0fe4f81.webp",
            "alt": "Sun Pool Lakeside storefront"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-f81bc4ced98399d1292e57c181e9cced73adca8c5d4eb050bb858fd3b985a20a-08e498519824461a81886867ac1fb6ff.webp",
            "alt": "Sun Pool showroom interior"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-a8ff38b435438d18c558d58a1d1647e9ef0af72f3a07626753d85f80fe8c5036-d3c72d2c2a9b4f4892ed801fa67e1c19.webp",
            "alt": "Family in the Sun Pool showroom"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-aa3be67b270c5e3fa78ec0e8fdebc4869a0a07b2b232fb82ad3a79c20798737f-9def32e2de7b4a4a8d8d8cac8560aaf5.webp",
            "alt": "Hydropool Signature 679 Platinum"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-8eba60b762646c71cf807c93c7a6ac11368a549d96ad8a677808c8e0b9ac79d1-3f767e12d3844d469c2e534530025a62.webp",
            "alt": "Hydropool AquaTrainer 14AX"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-8e2b67a85ff075d3222c96ac9cfb411497e1b5e1cd489bda9d56bcd7a32ae018-330a37f2850a4429967d5eadfae889c1.webp",
            "alt": "Hydropool Serenity 6600"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-2319e13e8b089ac3035349e7624102044ff0328a96014e8246b4ea644afd9358-2014bd136c3849a88a278a7dde7a0a50.webp",
            "alt": "DreamMaker Comfort 2300S Suite"
          },
          {
            "src": "https://pub-17e311eaecb5458ab28a18fbddcf65a8.r2.dev/clients/17-sun-pool-spa-supply/library/library-9e7fbdc5c170d3c85d8a4a7bb633d2422e0468d2d30b9aec5634e1c279361e3b-f39f3d9d0b9f480299848790f718ed4b.webp",
            "alt": "DreamMaker Cabana 3500L Suite"
          }
        ]
      },
      {
        "type": "splitcards",
        "heading": "Visit the Lakeside showroom",
        "items": [
          {
            "title": "Visit the Lakeside showroom",
            "body": "12473 Woodside Ave, Suite C. Real Hydropool and DreamMaker units filled and running — stop by Mon–Sat or Sunday until 2.",
            "image": null,
            "showAddress": true,
            "showHours": true,
            "actions": [
              {
                "label": "Get directions",
                "href": "/visit-us",
                "style": "primary"
              }
            ]
          }
        ]
      },
      {
        "type": "splitcards",
        "eyebrow": "Visit the showroom",
        "heading": "Worth the drive",
        "items": [
          {
            "title": "See them filled and running",
            "body": "Photos don't tell you how a shell fits your body or how strong the jets are. Ten minutes in the showroom answers what hours of research can't.",
            "image": null,
            "showAddress": true,
            "showHours": true,
            "actions": [
              {
                "label": "Learn more",
                "href": "/inventory",
                "style": "primary"
              }
            ]
          },
          {
            "title": "Talk to people who own them",
            "body": "Our team uses what we sell. Ask about maintenance, water care, and real running costs — you'll get straight answers, not a script.",
            "image": null,
            "showAddress": false,
            "showHours": false,
            "actions": [
              {
                "label": "Learn more",
                "href": "/visit-us",
                "style": "primary"
              }
            ]
          }
        ]
      },
      {
        "type": "steps",
        "eyebrow": "How it works",
        "heading": "From first visit to first soak",
        "items": [
          {
            "title": "Come see them in person",
            "body": "Walk the floor, ask questions, and compare models side by side with someone who knows them."
          },
          {
            "title": "Get your out-the-door price",
            "body": "One number in writing — unit, delivery, and setup — so you can decide with zero guesswork."
          },
          {
            "title": "We handle the rest",
            "body": "Delivery, placement, and startup guidance, plus a local team you can actually call afterward."
          }
        ]
      },
      {
        "type": "faq",
        "eyebrow": "Got questions?",
        "heading": "Good questions to ask",
        "items": [
          {
            "q": "How much does a hot tub actually cost?",
            "a": "It depends on size, seating, and insulation — that's why we quote a single out-the-door number that includes delivery and setup, not a teaser price."
          },
          {
            "q": "What does delivery involve?",
            "a": "We'll help you confirm access, placement, and the pad or surface before scheduling, so delivery day has no surprises."
          },
          {
            "q": "What do I need to run one at home?",
            "a": "Most spas need a level surface and a dedicated electrical circuit — we'll walk you through exactly what your model needs before you buy."
          },
          {
            "q": "Can I finance it?",
            "a": "In many cases yes — ask in store and we'll walk you through the current financing options and what they'd look like monthly."
          }
        ]
      },
      {
        "type": "trust",
        "items": [
          "Family-owned since 1978",
          "Lakeside showroom",
          "Out-the-door pricing",
          "4.7★ from 48 Google reviews",
          "Local crew after the sale"
        ],
        "logos": []
      },
      {
        "type": "bignumber",
        "value": "47",
        "label": "years serving East County",
        "claim": null
      },
      {
        "type": "ctaband",
        "eyebrow": null,
        "heading": "Ready when you are",
        "body": "Come walk the floor, or start with a quick text — either way you'll get real local pricing without the runaround.",
        "actions": [
          {
            "label": "Request Pricing",
            "href": "/find-your-match",
            "style": "primary"
          },
          {
            "label": "Text (619) 561-8587",
            "href": "sms:+16195618587",
            "style": "secondary"
          }
        ],
        "footnote": null,
        "tone": "dark"
      }
    ],
    "disclosures": []
  },
  "integrations": {
    "d1BindingName": "DB",
    "r2BindingName": "PRODUCT_IMAGES",
    "ghl": {
      "enabled": true
    },
    "meta": {
      "enabled": false
    },
    "zaraz": {
      "enabled": false
    },
    "sentry": {
      "enabled": false
    }
  }
};
